import os
import platform

global uname
uname = platform.uname()


if uname.system == "Windows":
    print("Module Installer (DEVELOPMENT)")

    os.system("python.exe -m pip install getpass")
    os.system("python.exe -m pip install speedtest")
    os.system("python.exe -m pip install geocoder")
    os.system("python.exe -m pip install wget")
    os.system("python.exe -m pip install pyvim")
    os.system("python.exe -m pip install requests")
    os.system("python.exe -m pip install pandas")
    os.system("python.exe -m pip install blessed")
    os.system("python.exe -m pip install openai")
    os.system("python.exe -m pip install openai[wandb]")
    os.system("python.exe -m pip install openai[embeddings]")
    os.system("python.exe -m pip install openai[datalib]")
    os.system("python.exe -m pip install python-requests-bitcoinrpc")
    os.system("python.exe -m pip install click")
    os.system("python.exe -m pip install bitcoinrpc")
    os.system("python.exe -m pip install bitcoinlib")
    os.system("python.exe -m pip install HDWallet")
    os.system("python.exe -m pip install sqlalchemy")
    os.system("python.exe -m pip install Flask-SQLAlchemy")
    os.system("python.exe -m pip install pyuac")
    os.system("python.exe -m pip install pypiwin32")
else:
    print("Module Installer (DEVELOPMENT)")

    os.system("python -m pip install getpass")
    os.system("python -m pip install speedtest")
    os.system("python -m pip install geocoder")
    os.system("python -m pip install wget")
    os.system("python -m pip install pyvim")
    os.system("python -m pip install requests")
    os.system("python -m pip install pandas")
    os.system("python -m pip install blessed")
    os.system("python -m pip install openai")
    os.system("python -m pip install openai[wandb]")
    os.system("python -m pip install openai[embeddings]")
    os.system("python -m pip install openai[datalib]")
    os.system("python -m pip install python-requests-bitcoinrpc")
    os.system("python -m pip install click")
    os.system("python -m pip install bitcoinrpc")
    os.system("python -m pip install bitcoinlib")
    os.system("python -m pip install HDWallet")
    os.system("python -m pip install sqlalchemy")
    os.system("python -m pip install Flask-SQLAlchemy")
    os.system("python -m pip install pyuac")
    os.system("python -m pip install pypiwin32")