import os

print("Module Installer (DEVELOPMENT)")

os.system("pip install getpass")
os.system("pip install speedtest")
os.system("pip install geocoder")
os.system("pip install wget")
os.system("pip install pyvim")
os.system("pip install requests")
os.system("pip install pandas")
os.system("pip install blessed")
os.system("pip install openai")
os.system("pip install openai[wandb]")
os.system("pip install openai[embeddings]")
os.system("pip install openai[datalib]")
os.system("pip install python-requests-bitcoinrpc")
os.system("pip install click")
os.system("pip install bitcoinrpc")
os.system("pip install bitcoinlib")
os.system("pip install HDWallet")
os.system("pip install sqlalchemy")
os.system("pip install Flask-SQLAlchemy")